title: 日記がてら猫の記録
author: kb9ut
description: > # this means to ignore newlines until "baseurl:"
  日記がてら猫の記録

# social links
twitter_username: kb9ut
github_username: kb9ut

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
